[package]
name = "rust_tutorials"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
ratatui = "0.30.0"
crossterm = "0.29.0"
strum_macros = "0.28.0"
cpal = "0.15.3"
rodio = "0.22.2"
audio-recorder-rs = {git = "https://github.com/mappa-ai/audio-recorder-rs.git", branch = "main", commit = "aeecd8a"}
hound = "3.5.1"
morsify = "0.2.0"
statrs = "0.18.0"

[[bin]]
name = "rust_tutorials"
path = "src/main.rs"
